source 'http://rubygems.org'

gem 'discordrb'
gem 'yourub'
gem 'tumblr_client'
gem 'twitter-text'
gem 'json'
gem 'multi_json'
gem 'net_http_ssl_fix'
gem 'google_custom_search_api'
gem 'httparty'
gem 'pry'
gem 'gemstone'
gem 'nokogiri'
gem 'john-doe'
gem 'cleverbot_io'
gem 'cleverbot-api'